version: 2
jobs:
  build:
    docker:
      - image: node:8
    steps:
      - checkout
      - run: yarn --version

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          - v1-dependencies-

      - run: npm install

      - run: npm run lint

      - run: npm run test

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          